@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJmaXJlc3RhcnRlciIsImV4cCI6MTcwMDAzMjMxNywiaWF0IjoxNzAwMDMwNTE3LCJpc3MiOiJmaXJlc3RhcnRlciIsImp0aSI6IjM5MzgxZTVhLTM3OTEtNGJmOS1hNDllLWU0ODdmMDIyMzE4ZSIsIm5iZiI6MTcwMDAzMDUxNiwic3ViIjoiOCIsInR5cCI6ImFjY2VzcyJ9.S0MGRUT7fYRULericvzhzlEl94Pl5G4njcL5EuYm-qGCCClJqtlGQT5hXtWXz5gnDG4PvGf4n4fqGoX-wm2NXA

### List all tasks
GET http://localhost:4000/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Get a single task by ID
GET http://localhost:4000/api/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Create a new task
POST http://localhost:4000/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "task": {
     "title": "3rd Task",
     "completed": false
   }
}

###

### Update an existing task
PUT http://localhost:4000/api/tasks/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "task": {
     "title": "Updated 3rd Title",
     "completed": true
   }
}

###

### Delete a task
DELETE http://localhost:4000/api/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### List all users
GET http://localhost:4000/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Get a single user by ID
GET http://localhost:4000/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Create a new user
POST http://localhost:4000/api/users
Content-Type: application/json

{
   "user": {
     "email": "monsythejrt@exampsc",
     "password": "Cut1epass!"
   }
}

###

### Update an existing user
PUT http://localhost:4000/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "user": {
     "email": "updateduser@example.com",
     "password_hash": "updatedhashedpassword"
   }
}

###

### Delete a user
DELETE http://localhost:4000/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Login and receive token
POST http://localhost:4000/api/sessions
Content-Type: application/json

{
  "email": "monsythejrt@example.com",
  "password": "Cutepassw0rd!"
}

### Refresh Access Token
POST http://localhost:4000/api/refresh_token
Content-Type: application/json

{
  "refresh_token": "B67eLYMo1Fj6hITkmFH5dgLquZPbkP1w7SH-lBdzwKRGVFj2bfH-7Ac-WwYOsnAcURI6RQMQ0MMWwAZoAeGLuw=="
}

### Delete session with refresh token
DELETE http://localhost:4000/api/sessions
Content-Type: application/json

{
  "refresh_token": "leRnsZZRFKiRAkSRlYzAu902WBT6ts0aEYvqVpIftZzD6RDEYOJiLJ--H4N01bmY_zZEpNtwX2ToYGjPD7yTkQ=="
}
