@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJmaXJlc3RhcnRlciIsImV4cCI6MTcwMjk3Nzc2NCwiaWF0IjoxNzAyOTc1OTY0LCJpc3MiOiJmaXJlc3RhcnRlciIsImp0aSI6ImQ3MTg5YmQzLTk1ZDQtNDgzNi1hODgxLTViMmRjZGQ5MDg5MCIsIm5iZiI6MTcwMjk3NTk2Mywic3ViIjoiMSIsInR5cCI6ImFjY2VzcyIsInVzZXJfaWQiOjF9.ieP27xBXEZQjulNapeT0ygulDb_qbFJHPmb0srmz3T4IGgUiv0BEJLubQ5ci9ckOBfEgkQrMDKWZ2qTgVVjCfw

### List all tasks
GET http://localhost:4000/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Get a single task by ID
GET http://localhost:4000/api/tasks/17
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Create a new task
POST http://localhost:4000/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "task": {
     "title": "User associated task num 5",
     "completed": false,
     "rank": "1"
   }
}

###

### Update an existing task
PUT http://localhost:4000/api/tasks/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "task": {
     "title": "Updated New Task",
     "completed": true
   }
}

###

### Delete a task
DELETE http://localhost:4000/api/tasks/4
Content-Type: application/json
Authorization: Bearer {{token}}

###

### List all users
GET http://localhost:4000/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Get a single user by ID
GET http://localhost:4000/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Create a new user
POST http://localhost:4000/api/users
Content-Type: application/json

{
   "user": {
     "email": "monsythejrt@example.com",
     "password": "Cut1epass!"
   }
}

###

### Update an existing user
PUT http://localhost:4000/api/users/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "user": {
    "email": "bridgitmendler+updated@gmail.com",
    "permission_id": "1"
   }
}

###

### Delete a user
DELETE http://localhost:4000/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Login and receive token
POST http://localhost:4000/api/sessions
Content-Type: application/json

{
  "email": "monsythejrt@example.com",
  "password": "Cut1epass!"
}

### Refresh Access Token
POST http://localhost:4000/api/refresh_token
Content-Type: application/json

{
  "refresh_token": "B67eLYMo1Fj6hITkmFH5dgLquZPbkP1w7SH-lBdzwKRGVFj2bfH-7Ac-WwYOsnAcURI6RQMQ0MMWwAZoAeGLuw=="
}

### Delete session with refresh token
DELETE http://localhost:4000/api/sessions
Content-Type: application/json

{
  "refresh_token": "leRnsZZRFKiRAkSRlYzAu902WBT6ts0aEYvqVpIftZzD6RDEYOJiLJ--H4N01bmY_zZEpNtwX2ToYGjPD7yTkQ=="
}
